version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend/fuse_connection.cfg:/app/backend/fuse_connection.cfg
    environment:
      - PORT=5000

    command: ["sh", "/app/start.sh"]
   
